// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATmosaEG45_yrOS-_IXl7H1SMt9y-gd8Q',
    appId: '1:195136676856:android:ef960a14247d52f663ac0d',
    messagingSenderId: '195136676856',
    projectId: 'spotmizoram',
    storageBucket: 'spotmizoram.firebasestorage.app',
    databaseURL:
        'https://spotmizoram-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzuHqzWDRHWZcT7WdnCNVpvQbK5VPYvW0',
    appId: '1:195136676856:ios:e1f64f535571b9f663ac0d',
    messagingSenderId: '195136676856',
    projectId: 'spotmizoram',
    storageBucket: 'spotmizoram.firebasestorage.app',
    iosClientId:
        '195136676856-h59hc87309qfparsv735jcdoocndct4g.apps.googleusercontent.com',
    iosBundleId: 'com.hillstech.spotmizoram',
    databaseURL:
        'https://spotmizoram-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
